
package com.ps.interfaces;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author JC
 */
public class MainInterface extends UserInterface {

    private static MainInterface singleton;
    
    /**
     * Creates new form MainInterface
     */
    private MainInterface() {
        initComponents();
        
        // Settings
        jPanel1.setSize(400, 540);
        getContentPane().setBackground(new Color(64, 64, 64));
        
        this.newOrderBtn.setBackground(new Color(51, 51, 51));
        this.existingOrdersBtn.setBackground(new Color(51, 51, 51));
        this.browseCatalogBtn.setBackground(new Color(51, 51, 51));
        this.recordDeliveryBtn.setBackground(new Color(51, 51, 51));
        
        this.newOrderBtn.setForeground(Color.WHITE);
        this.existingOrdersBtn.setForeground(Color.WHITE);
        this.browseCatalogBtn.setForeground(Color.WHITE);
        this.recordDeliveryBtn.setForeground(Color.WHITE);
        
        this.catalogPanelTitleSeperator.setOpaque(true);
        this.catalogPanelTitleSeperator.setForeground(new Color(0, 255, 255).brighter());
        this.catalogPanelTitleSeperator.setBackground(new Color(64, 64, 64));
        
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public static MainInterface getInstance() {
        if(singleton == null) {
            singleton = new MainInterface();
        } 
        return singleton;
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        catalogPanelTitleSeperator = new javax.swing.JSeparator();
        browseCatalogBtn = new javax.swing.JButton();
        newOrderBtn = new javax.swing.JButton();
        existingOrdersBtn = new javax.swing.JButton();
        recordDeliveryBtn = new javax.swing.JButton();
        userComboBox = new javax.swing.JComboBox();
        catalogPanelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        siteField = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(400, 540));
        setMinimumSize(new java.awt.Dimension(400, 540));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 540));

        browseCatalogBtn.setText("Browse Catalog");
        browseCatalogBtn.setToolTipText("Create a new order");
        browseCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseCatalogBtnActionPerformed(evt);
            }
        });

        newOrderBtn.setText("New Order");
        newOrderBtn.setToolTipText("Create a new order");
        newOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderBtnActionPerformed(evt);
            }
        });

        existingOrdersBtn.setText("Existing Orders");
        existingOrdersBtn.setToolTipText("Create a new order");
        existingOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingOrdersBtnActionPerformed(evt);
            }
        });

        recordDeliveryBtn.setText("Record Delivery");
        recordDeliveryBtn.setToolTipText("Create a new order");
        recordDeliveryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordDeliveryBtnActionPerformed(evt);
            }
        });

        userComboBox.setBackground(new java.awt.Color(51, 51, 51));
        userComboBox.setForeground(new java.awt.Color(255, 255, 255));
        userComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kumar Kalla", "Elizabeth Webber" }));
        userComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboBoxActionPerformed(evt);
            }
        });

        catalogPanelTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        catalogPanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        catalogPanelTitle.setText("Procurement Management App - Welcome!");

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Site:");

        siteField.setBackground(new java.awt.Color(51, 51, 51));
        siteField.setForeground(new java.awt.Color(255, 255, 255));
        siteField.setText("Sheffield");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(existingOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recordDeliveryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(siteField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(catalogPanelTitle)
                    .addContainerGap(123, Short.MAX_VALUE))
                .addComponent(catalogPanelTitleSeperator))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(newOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(existingOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recordDeliveryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(browseCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(catalogPanelTitle)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(catalogPanelTitleSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(502, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseCatalogBtnActionPerformed
        CatalogUI catalogUI = CatalogUI.getInstance();
        catalogUI.setMode("browse");
        getOption(catalogUI);
    }//GEN-LAST:event_browseCatalogBtnActionPerformed

    private void newOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderBtnActionPerformed
        PlaceOrderUI placeOrderUI = PlaceOrderUI.getInstance();
        String site = siteField.getText();
        placeOrderUI.setSite(site);
        getOption(placeOrderUI);
    }//GEN-LAST:event_newOrderBtnActionPerformed

    private void existingOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingOrdersBtnActionPerformed
        ViewOrdersUI viewOrderUI = ViewOrdersUI.getInstance();
        getOption(viewOrderUI);
    }//GEN-LAST:event_existingOrdersBtnActionPerformed

    private void recordDeliveryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordDeliveryBtnActionPerformed
        DeliveryUI deliveryUI = DeliveryUI.getInstance();
        getOption(deliveryUI);
    }//GEN-LAST:event_recordDeliveryBtnActionPerformed

    private void userComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboBoxActionPerformed
        // Doing this as there is no User class and therefore no way of adding user permissions
        if(userComboBox.getSelectedItem() == "Kumar Kalla") {
            browseCatalogBtn.setVisible(true);
            newOrderBtn.setVisible(true);
            existingOrdersBtn.setVisible(true);
            recordDeliveryBtn.setVisible(true);
        } else if(userComboBox.getSelectedItem() == "Elizabeth Webber") {
            newOrderBtn.setVisible(false);
            recordDeliveryBtn.setVisible(false);
        }
    }//GEN-LAST:event_userComboBoxActionPerformed

    public void getOption(UserInterface ui) {
        ui.setPosition(this.getX(), this.getY());
        ui.Run();
        this.setVisible(false);
    }
    
    public void Run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        MainInterface that = this;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                that.setVisible(true);
            }
        });
    }
    
    @Override
    public void setPosition(int x, int y) {
        this.setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseCatalogBtn;
    private javax.swing.JLabel catalogPanelTitle;
    private javax.swing.JSeparator catalogPanelTitleSeperator;
    private javax.swing.JButton existingOrdersBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton newOrderBtn;
    private javax.swing.JButton recordDeliveryBtn;
    private javax.swing.JTextField siteField;
    private javax.swing.JComboBox userComboBox;
    // End of variables declaration//GEN-END:variables
}
