package com.ps.interfaces;

import com.ps.model.Delivery;
import com.ps.model.Item;
import com.ps.model.Order;
import com.ps.model.OrderLine;
import com.ps.model.SetOfDeliveries;
import com.ps.model.SetOfOrders;
import java.awt.Color;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 * User Interface for displaying a list
 * of all current orders. Consists of 2 separate
 * JPanel which provide 2 views. The first view
 * is a list of all available orders. The second view
 * is a details of a specific order based on the
 * selection of the user.
 * @author JCollinge
 */
public class ViewOrdersUI extends UserInterface {

    private static ViewOrdersUI singleton;
    private SetOfOrders orders;
    private DefaultListModel<Order> ordersModel;
    private DefaultListModel<Item> orderModel;
    private DefaultListModel<Integer> orderQuantityModel;
    
    private boolean siteFiltered = false;
    private boolean dateFiltered = false;
    private boolean supplierFiltered = false;
    private boolean ascending = true;
    private boolean activeOrdersOnly = true;
    
    /**
     * Ctor -  initialise data and Swing componenets
     */
    private ViewOrdersUI() {
        
        ordersModel =  new DefaultListModel();
        orderModel = new DefaultListModel();
        orderQuantityModel = new DefaultListModel();
       
        initComponents();
        //displayCurrentOrders();
        activeOrdersOnlyBtn.setSelected(false);
        activeOrdersOnly = false;
        
        //Settings
        jLayeredPane1.setPreferredSize(new Dimension(400, 540));
        getContentPane().setBackground(new Color(64, 64, 64));
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        orderPanel.setVisible(false);
        ordersPanel.setVisible(true);
    }

    /**
     * Lazy load and get singleton instance
     * @return 
     */
    public static ViewOrdersUI getInstance() {
        if (singleton == null) {
            singleton = new ViewOrdersUI();
        }
        return singleton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ordersPanel = new javax.swing.JPanel();
        locationTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        supplierTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        matchingExistingOrders = new javax.swing.JList();
        returnToMainMenuBtn = new javax.swing.JButton();
        filterBySiteBtn = new javax.swing.JToggleButton();
        filterByDateBtn = new javax.swing.JToggleButton();
        filterBySupplierBtn = new javax.swing.JToggleButton();
        ascendBtn = new javax.swing.JToggleButton();
        descendBtn = new javax.swing.JToggleButton();
        activeOrdersOnlyBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        orderPanel = new javax.swing.JPanel();
        orderPanelTitle = new javax.swing.JLabel();
        OrderPanelTitleSeparator = new javax.swing.JSeparator();
        orderDateLabel = new javax.swing.JLabel();
        orderDateValue = new javax.swing.JLabel();
        itemsOrderedLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsOrderedList = new javax.swing.JList();
        deliverDateLabel = new javax.swing.JLabel();
        deliveryDateValue = new javax.swing.JLabel();
        signedForByLabel = new javax.swing.JLabel();
        signedForByValue = new javax.swing.JLabel();
        deliveryStatusLabel = new javax.swing.JLabel();
        deliveryStatusValue = new javax.swing.JLabel();
        printAuditTrailBtn = new javax.swing.JButton();
        returnToExistingOrdersBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemsOrderedQuantities = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(400, 540));

        ordersPanel.setBackground(new java.awt.Color(0, 0, 0));
        ordersPanel.setForeground(new java.awt.Color(255, 255, 255));

        locationTextField.setText("Sheffield S1");
        locationTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                locationTextFieldKeyReleased(evt);
            }
        });

        dateTextField.setText(new SimpleDateFormat("dd/M/yyyy").format(new Date()));
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });
        dateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateTextFieldKeyReleased(evt);
            }
        });

        supplierTextField.setText("Type here");
        supplierTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierTextFieldKeyReleased(evt);
            }
        });

        matchingExistingOrders.setBackground(new java.awt.Color(0, 0, 0));
        matchingExistingOrders.setForeground(new java.awt.Color(255, 255, 255));
        matchingExistingOrders.setModel(ordersModel);
        matchingExistingOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                matchingExistingOrdersMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(matchingExistingOrders);

        returnToMainMenuBtn.setBackground(new java.awt.Color(51, 51, 51));
        returnToMainMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        returnToMainMenuBtn.setText("Return to Main Menu");
        returnToMainMenuBtn.setBorder(null);
        returnToMainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMainMenuBtnActionPerformed(evt);
            }
        });

        filterBySiteBtn.setBackground(new java.awt.Color(51, 51, 51));
        filterBySiteBtn.setForeground(new java.awt.Color(255, 255, 255));
        filterBySiteBtn.setText("Site Filtered");
        filterBySiteBtn.setBorder(null);
        filterBySiteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBySiteBtnActionPerformed(evt);
            }
        });

        filterByDateBtn.setBackground(new java.awt.Color(51, 51, 51));
        filterByDateBtn.setForeground(new java.awt.Color(255, 255, 255));
        filterByDateBtn.setText("Filter by Date");
        filterByDateBtn.setBorder(null);
        filterByDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterByDateBtnActionPerformed(evt);
            }
        });

        filterBySupplierBtn.setBackground(new java.awt.Color(51, 51, 51));
        filterBySupplierBtn.setForeground(new java.awt.Color(255, 255, 255));
        filterBySupplierBtn.setText("Filter by Supplier");
        filterBySupplierBtn.setBorder(null);
        filterBySupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBySupplierBtnActionPerformed(evt);
            }
        });

        ascendBtn.setBackground(new java.awt.Color(51, 51, 51));
        ascendBtn.setForeground(new java.awt.Color(255, 255, 255));
        ascendBtn.setText("Ascend");
        ascendBtn.setBorder(null);
        ascendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascendBtnActionPerformed(evt);
            }
        });

        descendBtn.setBackground(new java.awt.Color(51, 51, 51));
        descendBtn.setForeground(new java.awt.Color(255, 255, 255));
        descendBtn.setText("Descend");
        descendBtn.setBorder(null);
        descendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descendBtnActionPerformed(evt);
            }
        });

        activeOrdersOnlyBtn.setBackground(new java.awt.Color(51, 51, 51));
        activeOrdersOnlyBtn.setForeground(new java.awt.Color(255, 255, 255));
        activeOrdersOnlyBtn.setText("Active Orders Only");
        activeOrdersOnlyBtn.setBorder(null);
        activeOrdersOnlyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeOrdersOnlyBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Viewing Orders - Filtered by ");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout ordersPanelLayout = new javax.swing.GroupLayout(ordersPanel);
        ordersPanel.setLayout(ordersPanelLayout);
        ordersPanelLayout.setHorizontalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(returnToMainMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ordersPanelLayout.createSequentialGroup()
                            .addComponent(ascendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(descendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(activeOrdersOnlyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ordersPanelLayout.createSequentialGroup()
                            .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(locationTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplierTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(15, 15, 15)
                            .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(filterByDateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(filterBySiteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(filterBySupplierBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        ordersPanelLayout.setVerticalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ordersPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filterBySiteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterByDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterBySupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ascendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activeOrdersOnlyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnToMainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        orderPanel.setBackground(new java.awt.Color(0, 0, 0));
        orderPanel.setPreferredSize(new java.awt.Dimension(400, 540));

        orderPanelTitle.setBackground(new java.awt.Color(0, 0, 0));
        orderPanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        orderPanelTitle.setText("Audit - Order Id: 00127653");

        OrderPanelTitleSeparator.setBackground(new java.awt.Color(0, 0, 0));
        OrderPanelTitleSeparator.setForeground(new java.awt.Color(0, 204, 255));

        orderDateLabel.setBackground(new java.awt.Color(0, 0, 0));
        orderDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        orderDateLabel.setText("Order Date:");

        orderDateValue.setBackground(new java.awt.Color(0, 0, 0));
        orderDateValue.setForeground(new java.awt.Color(255, 255, 255));
        orderDateValue.setText("12/10/2013");

        itemsOrderedLabel.setBackground(new java.awt.Color(0, 0, 0));
        itemsOrderedLabel.setForeground(new java.awt.Color(255, 255, 255));
        itemsOrderedLabel.setText("Items Ordered");

        itemsOrderedList.setBackground(new java.awt.Color(0, 0, 0));
        itemsOrderedList.setForeground(new java.awt.Color(255, 255, 255));
        itemsOrderedList.setModel(orderModel);
        jScrollPane2.setViewportView(itemsOrderedList);

        deliverDateLabel.setBackground(new java.awt.Color(0, 0, 0));
        deliverDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        deliverDateLabel.setText("Delivery Date:");

        deliveryDateValue.setBackground(new java.awt.Color(0, 0, 0));
        deliveryDateValue.setForeground(new java.awt.Color(255, 255, 255));
        deliveryDateValue.setText("19/10/2013");

        signedForByLabel.setBackground(new java.awt.Color(0, 0, 0));
        signedForByLabel.setForeground(new java.awt.Color(255, 255, 255));
        signedForByLabel.setText("Signed For By:");

        signedForByValue.setBackground(new java.awt.Color(0, 0, 0));
        signedForByValue.setForeground(new java.awt.Color(255, 255, 255));
        signedForByValue.setText("Kumar Kalla");

        deliveryStatusLabel.setBackground(new java.awt.Color(0, 0, 0));
        deliveryStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        deliveryStatusLabel.setText("Delivery Status:");

        deliveryStatusValue.setBackground(new java.awt.Color(0, 0, 0));
        deliveryStatusValue.setForeground(new java.awt.Color(255, 255, 255));
        deliveryStatusValue.setText("Accepted");

        printAuditTrailBtn.setBackground(new java.awt.Color(51, 51, 51));
        printAuditTrailBtn.setForeground(new java.awt.Color(255, 255, 255));
        printAuditTrailBtn.setText("Print Audit Trail");
        printAuditTrailBtn.setBorder(null);
        printAuditTrailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printAuditTrailBtnActionPerformed(evt);
            }
        });

        returnToExistingOrdersBtn.setBackground(new java.awt.Color(51, 51, 51));
        returnToExistingOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        returnToExistingOrdersBtn.setText("Return to Existing Orders");
        returnToExistingOrdersBtn.setBorder(null);
        returnToExistingOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToExistingOrdersBtnActionPerformed(evt);
            }
        });

        itemsOrderedQuantities.setBackground(new java.awt.Color(0, 0, 0));
        itemsOrderedQuantities.setForeground(new java.awt.Color(255, 255, 255));
        itemsOrderedQuantities.setModel(orderQuantityModel);
        jScrollPane3.setViewportView(itemsOrderedQuantities);

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderPanelTitleSeparator)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(orderDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderDateValue))
                            .addComponent(itemsOrderedLabel)))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(orderPanelTitle))
                    .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, orderPanelLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, orderPanelLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(printAuditTrailBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(returnToExistingOrdersBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                                .addGroup(orderPanelLayout.createSequentialGroup()
                                    .addComponent(deliveryStatusLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(deliveryStatusValue))
                                .addGroup(orderPanelLayout.createSequentialGroup()
                                    .addComponent(signedForByLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(signedForByValue))
                                .addGroup(orderPanelLayout.createSequentialGroup()
                                    .addComponent(deliverDateLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(deliveryDateValue))))))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderPanelTitle)
                .addGap(12, 12, 12)
                .addComponent(OrderPanelTitleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderDateLabel)
                    .addComponent(orderDateValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemsOrderedLabel)
                .addGap(18, 18, 18)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliverDateLabel)
                    .addComponent(deliveryDateValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signedForByLabel)
                    .addComponent(signedForByValue))
                .addGap(37, 37, 37)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryStatusLabel)
                    .addComponent(deliveryStatusValue))
                .addGap(18, 18, 18)
                .addComponent(printAuditTrailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnToExistingOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(orderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(orderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1.setLayer(ordersPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(orderPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Called when the return to existing order button is pressed. Should
     * handle the transition from the specific order panel back to a list
     * of all orders
     * @param evt 
     */
    private void returnToExistingOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToExistingOrdersBtnActionPerformed
        dateTextField.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        supplierTextField.setText("Type here");
        locationTextField.setText("Sheffield S1");
        orderPanel.setVisible(false);
        ordersPanel.setVisible(true);
    }//GEN-LAST:event_returnToExistingOrdersBtnActionPerformed

    /**
     * Prints an audit trail. The class diagram does not have any implementation or
     * reference to an audit trail so we are unsure what this is required to do.
     * @param evt 
     */
    private void printAuditTrailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printAuditTrailBtnActionPerformed
        System.out.println("Audit trail: Processed(01/01/2015), Dispatched(01/01/2015), Delivered(01/01/2015)");
    }//GEN-LAST:event_printAuditTrailBtnActionPerformed

    /**
     * Called when the active orders button is pressed. There is not implementation
     * or reference to this in the class diagram so we are unsure what this should
     * do.
     * @param evt 
     */
    private void activeOrdersOnlyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeOrdersOnlyBtnActionPerformed
        activeOrdersOnly = !activeOrdersOnly;
        System.out.println("Active only: " + activeOrdersOnly);
        activeOrdersOnlyBtn.setSelected(activeOrdersOnly);
        if(dateFiltered) {
            dateFiltered = false;
            filterByDateBtnActionPerformed(null);
        } else if(siteFiltered) {
            siteFiltered = false;
            filterBySiteBtnActionPerformed(null);
        } else if(supplierFiltered) {
            supplierFiltered = false;
            filterBySupplierBtnActionPerformed(null);
        } else {
            if(activeOrdersOnly) {
                ordersModel.clear();
                for(Order order : orders.getOpenOrders()) {
                    ordersModel.addElement(order);
                }
            } else {
                ordersModel.clear();
                for(Order order : orders.getAllOrders()) {
                    ordersModel.addElement(order);
                }
            }
        }
    }//GEN-LAST:event_activeOrdersOnlyBtnActionPerformed

    /**
     * Called when the descend button is pressed. Should sort the items into
     * descending order.
     * @param evt 
     */
    private void descendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descendBtnActionPerformed
        if(ascending) {
            reverseList();
            descendBtn.setSelected(true);
            ascendBtn.setSelected(false);
            ascending = false;
        }
    }//GEN-LAST:event_descendBtnActionPerformed

    /**
     * Called when the ascend button is pressed. Should sort the items
     * into ascending order.
     * @param evt 
     */
    private void ascendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascendBtnActionPerformed
        if(!ascending) {
            reverseList();
            descendBtn.setSelected(false);
            ascendBtn.setSelected(true);
            ascending = true;
        }
    }//GEN-LAST:event_ascendBtnActionPerformed

    /**
     * Should filter by supplier
     * @param evt 
     */
    private void filterBySupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBySupplierBtnActionPerformed
        
        String filterTerm = supplierTextField.getText();
        
        if(filterTerm.isEmpty()) {
            System.out.println("Filter term is empty");
            filterBySupplierBtn.setSelected(false);
            return;
        }
        
        if(supplierFiltered) {
            displayCurrentOrders();
            supplierFiltered = false;
        } else {
            // set flags
            supplierFiltered = true;
            dateFiltered = false;
            siteFiltered = false;
            // turn off site && date
            filterBySiteBtn.setSelected(false);
            filterByDateBtn.setSelected(false);

            String param = filterTerm;
            requestFilter("supplier", param);
        }
        
        if(!supplierFiltered && !dateFiltered && !siteFiltered) {
            System.out.println("no filter selected");
            if(activeOrdersOnly) {
                ordersModel.clear();
                for(Order order : orders.getOpenOrders()) {
                    ordersModel.addElement(order);
                }
            } else {
                ordersModel.clear();
                for(Order order : orders.getAllOrders()) {
                    ordersModel.addElement(order);
                }
            }
        }
    }//GEN-LAST:event_filterBySupplierBtnActionPerformed

    /**
     * Should filter by date
     * @param evt 
     */
    private void filterByDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterByDateBtnActionPerformed
        
        String filterTerm = dateTextField.getText();
        
        if(filterTerm.isEmpty()) {
            System.out.println("Filter term is empty");
            filterByDateBtn.setSelected(false);
            return;
        }
        
        if(dateFiltered) {
            displayCurrentOrders();
            dateFiltered = false;
        } else {
            // set flags
            dateFiltered = true;
            siteFiltered = false;
            supplierFiltered = false;
            // turn off site & supplier
            filterBySiteBtn.setSelected(false);
            filterBySupplierBtn.setSelected(false);

            String txt = filterTerm;
            SimpleDateFormat sdf = new SimpleDateFormat("d/M/yyyy");
            Date date = null;
            try {
                date = sdf.parse(txt);
            } catch (ParseException ex) {
                Logger.getLogger(ViewOrdersUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            requestFilter("date", date);

        }
        
       if(!supplierFiltered && !dateFiltered && !siteFiltered) {
            System.out.println("no filter selected");
            if(activeOrdersOnly) {
                ordersModel.clear();
                for(Order order : orders.getOpenOrders()) {
                    ordersModel.addElement(order);
                }
            } else {
                ordersModel.clear();
                for(Order order : orders.getAllOrders()) {
                    ordersModel.addElement(order);
                }
            }
        }
    }//GEN-LAST:event_filterByDateBtnActionPerformed

    /**
     * Should filter by site
     * @param evt 
     */
    private void filterBySiteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBySiteBtnActionPerformed
        
         String filterTerm = locationTextField.getText();
        
        if(filterTerm.isEmpty()) {
            System.out.println("Filter term is empty");
            filterBySiteBtn.setSelected(false);
            return;
        }
        
        if(siteFiltered) {
            displayCurrentOrders();
            siteFiltered = false;
        } else {
            // set flags
            siteFiltered = true;
            dateFiltered = false;
            supplierFiltered = false;
            // turn off data & supplier
            filterByDateBtn.setSelected(false);
            filterBySupplierBtn.setSelected(false);

            String param = filterTerm;
            requestFilter("site", param);
        }
        
        if(!supplierFiltered && !dateFiltered && !siteFiltered) {
            System.out.println("no filter selected");
            if(activeOrdersOnly) {
                ordersModel.clear();
                for(Order order : orders.getOpenOrders()) {
                    ordersModel.addElement(order);
                }
            } else {
                ordersModel.clear();
                for(Order order : orders.getAllOrders()) {
                    ordersModel.addElement(order);
                }
            }
        }
    }//GEN-LAST:event_filterBySiteBtnActionPerformed

    /**
     * Called when the return to main menu button is pressed. Should clear any
     * temporary data and handle the transition back to the main interface.
     * @param evt 
     */
    private void returnToMainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMainMenuBtnActionPerformed

        dateTextField.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        supplierTextField.setText("Type here");
        locationTextField.setText("Sheffield S1");
        
        MainInterface ui = MainInterface.getInstance();
        ui.setPosition(this.getX(), this.getY());
        
        this.setVisible(false);
        ui.Run();
    }//GEN-LAST:event_returnToMainMenuBtnActionPerformed

    /**
     * Called when an order has been selected by the user.
     * @param evt 
     */
    private void matchingExistingOrdersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchingExistingOrdersMouseReleased
        // User has selected an order
        Order selectedOrder = (Order)matchingExistingOrders.getSelectedValue();
        if(selectedOrder != null) {
            initialiseOrderPanel(selectedOrder);
        }       
    }//GEN-LAST:event_matchingExistingOrdersMouseReleased

    private void locationTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locationTextFieldKeyReleased
        System.out.println("Typing site filter");
        if(siteFiltered) {
            filterBySiteBtn.setSelected(false);
            filterBySiteBtnActionPerformed(null);
        }
    }//GEN-LAST:event_locationTextFieldKeyReleased

    private void dateTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTextFieldKeyReleased
        System.out.println("Typing date filtered");
        if(dateFiltered) {
            filterByDateBtn.setSelected(false);
            filterByDateBtnActionPerformed(null);
        }
    }//GEN-LAST:event_dateTextFieldKeyReleased

    private void supplierTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierTextFieldKeyReleased
        System.out.println("Typing supplier filtered");
        if(supplierFiltered) {
            filterBySupplierBtn.setSelected(false);
            filterBySupplierBtnActionPerformed(null);
        }
    }//GEN-LAST:event_supplierTextFieldKeyReleased

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    /**
     * Set default data and models for order panel
     * @param order 
     */
    private void initialiseOrderPanel(Order order) {
  
        orderModel.clear();
        orderQuantityModel.clear();
        
        SetOfDeliveries setOfDeliveries = SetOfDeliveries.getInstance();
        Delivery delivery = setOfDeliveries.getDeliveryByOrder(order);
        
        String date = null;
        String deliveryDate = null;
        String signedForBy = null;
        String deliveryStatus = null;
        
        if(delivery == null) {
            deliveryDate = "";
            signedForBy = "-";
            deliveryStatus = "Pending";
        } else {
            deliveryDate = "Not stored in delivery";
            signedForBy = delivery.getApprovedBy();
            deliveryStatus = delivery.getDeliveryStatus();
        }
        
        orderDateValue.setText(new SimpleDateFormat("dd/MM/yyyy").format(order.getOrderDate()));
        deliveryDateValue.setText(deliveryDate);
        signedForByValue.setText(signedForBy);
        deliveryStatusValue.setText(deliveryStatus);
        
        ArrayList<OrderLine> orderLines = order.getOrderLines();
        for(OrderLine orderLine : orderLines) {
            orderModel.addElement(orderLine.getItem());
            orderQuantityModel.addElement(orderLine.getQuantity());
        }
        
        ordersPanel.setVisible(false);
        orderPanel.setVisible(true);
    }
    
    /**
     * Main execution method for UserInterface
     */
    public void Run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrdersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrdersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrdersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrdersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        // closure
        final  ViewOrdersUI that = this;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                that.displayCurrentOrders();
                that.setVisible(true);
            }
        });
    }
    
    /**
     * Should reverse the model lists
     */
    private void reverseList() {
        ArrayList<Order> reversedList = new ArrayList<>();
        for(int i = ordersModel.size() - 1; i >= 0; i--) {
            reversedList.add(ordersModel.get(i));
        }
        ordersModel.clear();
        for(Order item : reversedList) {
            ordersModel.addElement((Order)item);
        }
    }

    /**
     * Displays all of the current orders
     */
    public void displayCurrentOrders() {
        orders = SetOfOrders.getInstance();
        if(activeOrdersOnly) {
            ordersModel.clear();
            for(Order order : orders.getOpenOrders()) {
                ordersModel.addElement(order);
            }
        } else {
            ordersModel.clear();
            for(Order order : orders.getAllOrders()) {
                ordersModel.addElement(order);
            }
        }
    }

    /**
     * Load all current orders. This is provided in the class diagram but
     * was not used.
     */
    public void loadOrders() {
    }

    /**
     * Will match a given filter to a filter implementation and update
     * the model.
     * @param filter
     * @param param
     */
    public void requestFilter(String filter, Object param) {
        if(param != null) {
            ArrayList<Order> matching = null;
            if(filter.equalsIgnoreCase("site")) {
                matching = orders.filterBySite((String)param);
            } else if(filter.equalsIgnoreCase("date")) {
                matching = orders.filterByDate((Date)param);
            } else if(filter.equalsIgnoreCase("supplier")) {
                matching = orders.filterBySupplier((String)param);
            }
            System.out.println("filtered:\n " + matching);
            
            ordersModel.clear();
            for(Order order : matching) {
                if(activeOrdersOnly) {
                    if(order.getOrderStatus().equals("Pending")) {
                        ordersModel.addElement(order);
                    }
                } else {
                    ordersModel.addElement(order);
                }
            } 
        }
    }

    @Override
    public void setPosition(int x, int y) {
        this.setLocation(x, y);
    }
    
    public int getPositionX()
    {
        return this.getX();
    }
    
    public int getPositionY()
    {
        return this.getY();
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator OrderPanelTitleSeparator;
    private javax.swing.JToggleButton activeOrdersOnlyBtn;
    private javax.swing.JToggleButton ascendBtn;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel deliverDateLabel;
    private javax.swing.JLabel deliveryDateValue;
    private javax.swing.JLabel deliveryStatusLabel;
    private javax.swing.JLabel deliveryStatusValue;
    private javax.swing.JToggleButton descendBtn;
    private javax.swing.JToggleButton filterByDateBtn;
    private javax.swing.JToggleButton filterBySiteBtn;
    private javax.swing.JToggleButton filterBySupplierBtn;
    private javax.swing.JLabel itemsOrderedLabel;
    private javax.swing.JList itemsOrderedList;
    private javax.swing.JList itemsOrderedQuantities;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JList matchingExistingOrders;
    private javax.swing.JLabel orderDateLabel;
    private javax.swing.JLabel orderDateValue;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JLabel orderPanelTitle;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JButton printAuditTrailBtn;
    private javax.swing.JButton returnToExistingOrdersBtn;
    private javax.swing.JButton returnToMainMenuBtn;
    private javax.swing.JLabel signedForByLabel;
    private javax.swing.JLabel signedForByValue;
    private javax.swing.JTextField supplierTextField;
    // End of variables declaration//GEN-END:variables

}
